### ISSUE TITLE
Unknown transform "name/cti/kebab"

### ISSUE THREAD

**Issue by traed** [amzn/style-dictionary#1311]
Getting the following error when trying to use [this transformer](https://www.npmjs.com/package/sd-tailwindcss-transformer). No clue what this means. Please help?

Error: 
Unknown transform "name/cti/kebab" found in platform "tailwind":
"name/cti/kebab" does not match the name of a registered transform.

    at transformConfig (file:///Users/mattias/Code/c2-tokens-test/node_modules/.pnpm/style-dictionary@4.0.1/node_modules/style-dictionary/lib/transform/config.js:95:11)
    at StyleDictionary.getPlatform (file:///Users/mattias/Code/c2-tokens-test/node_modules/.pnpm/style-dictionary@4.0.1/node_modules/style-dictionary/lib/StyleDictionary.js:561:28)
    at async StyleDictionary.buildPlatform (file:///Users/mattias/Code/c2-tokens-test/node_modules/.pnpm/style-dictionary@4.0.1/node_modules/style-dictionary/lib/StyleDictionary.js:840:44)
    at async Promise.all (index 0)
    at async StyleDictionary.buildAllPlatforms (file:///Users/mattias/Code/c2-tokens-test/node_modules/.pnpm/style-dictionary@4.0.1/node_modules/style-dictionary/lib/StyleDictionary.js:885:7)

Node.js v20.15.0

**Comment by jorenbroekema** [comment]
The built-in name transforms have been renamed to remove the `/cti` part so it's just `name/kebab` now. Need to adjust your config to use the correct name transform.

More info https://styledictionary.com/version-4/migration/#cti-reliance
