### ISSUE TITLE
Error: unknown transformGroup "custom/web" found in platform "web":

### ISSUE THREAD

**Issue by lusarz** [amzn/style-dictionary#292]
Steps to reproduce:

    cd ~/github
    git clone git@github.com:amzn/style-dictionary.git
    npm install
    cd ~/github/style-dictionary/examples/advanced/custom-transforms
    ~/github/style-dictionary/bin/style-dictionary build

Output:
    
    web
    /home/lukasz/github/style-dictionary/lib/transform/config.js:49
      throw new Error(err);
      ^

    Error: 
    Unknown transformGroup "custom/web" found in platform "web":
    "custom/web" does not match the name of a registered transformGroup.

    at transformConfig (/home/lukasz/github/style-dictionary/lib/transform/config.js:49:13)
    at Object.buildPlatform (/home/lukasz/github/style-dictionary/lib/buildPlatform.js:51:24)
    at /home/lukasz/github/style-dictionary/lib/buildAllPlatforms.js:33:10
    at /home/lukasz/github/style-dictionary/node_modules/lodash/lodash.js:4911:15
    at Function.forIn (/home/lukasz/github/style-dictionary/node_modules/lodash/lodash.js:12951:11)
    at Object.buildAllPlatforms (/home/lukasz/github/style-dictionary/lib/buildAllPlatforms.js:32:5)
    at Command.styleDictionaryBuild (/home/lukasz/github/style-dictionary/bin/style-dictionary:85:21)
    at Command.listener (/home/lukasz/github/style-dictionary/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:197:13)
    at Command.parseArgs (/home/lukasz/github/style-dictionary/node_modules/commander/index.js:654:12)

**Comment by dbanksdesign** [comment]
Because that example shows how to write custom transforms, you will need to use the node module rather than just calling the CLI command. That example has a npm script defined, 'build', which you will need to run instead, which will run this file:
https://github.com/amzn/style-dictionary/blob/master/examples/advanced/custom-transforms/build.js

Let me know if you have any other issues!

**Comment by lusarz** [comment]
Okay, now it works :)

I would like to get involved in the project - do you recommend any issue that I could take care of ?

**Comment by dbanksdesign** [comment]
Almost any issue would be good to start. What kind of work are you thinking about? Our docs could always use improving, like #286. If you want something easy and mundane, #281 is pretty easy. Or if you have an idea for an example, we are always looking for new examples.

**Comment by chazzmoney** [comment]
Should we add in some kind of note on that example to use the npm build?

**Comment by chazzmoney** [comment]
Also, looking forward to more contributions from you @lusarz - thanks!

**Comment by dbanksdesign** [comment]
Can we close this issue out?

**Comment by lusarz** [comment]
Yes
