### ISSUE TITLE
How can i make an independent executable which can be run anywhere without install the npm and node environment?

### ISSUE THREAD

**Issue by dymx101** [amzn/style-dictionary#368]
as i googled, it seems `pkg` is a pretty neat tool for this usage, but the executable it generated give me some error like this:

```
pkg/prelude/bootstrap.js:1185
      throw error;
      ^

Error: File '/**/style-dictionary/lib/common/templates/scss/map-flat.template' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:429:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:657:29)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:700:18)
    at Object.<anonymous> (/snapshot/style-dictionary/lib/common/formats.js)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31) {
  errno: -2,
  code: 'ENOENT',
  path: '/snapshot/style-dictionary/lib/common/templates/scss/map-flat.template',
  pkg: true
}
```

**Comment by dbanksdesign** [comment]
I am not familiar with pkg, you are trying to make an independent executable of the style-dictionary command? It seems from the error that file is not being bundled correctly and you need to add it as an asset. Just did a quick read of the [pkg docs](https://www.npmjs.com/package/pkg) and by default it does not include any non-javascript files, and the templates are not. It looks like if you tell pkg those are assets in the [configuration](https://www.npmjs.com/package/pkg#config).

**Comment by dbanksdesign** [comment]
Closing this, feel free to reopen it or file a new issue if you are still having an issue.
