### ISSUE TITLE
Specifications for property values

### ISSUE THREAD

**Issue by lukasoppermann** [amzn/style-dictionary#461]
Hey I really love the library,

I am currently working on a figma plugin to extract and prepare design tokens to be converted using the `style-dictionary`.  I feel it would be helpful to specify how certain properties should be defined, so that they can be reliably converted in a build step.

### Why is this important? Use case?
Design token are a new standard tool that is evolving. As far as I can see `amzn/style-dictionary` is one of the most used packages for this and thus as probably a huge impact on forming this new standard.

The documentation & specification is very well done for building the tooling around converting properties. However the creation and editing of properties is currently not that extensively documented and would need more documentation. 

#### How should units be specified?
Should they be included in the value e.g. `120%` or should a specific unit property be added like when exporting from figma?
```
"property": {
  "value": {
    "unit": "PERCENT",
    "value": 120
  }
}

## or

"property": {
  "value": 120,
  "unit": "PERCENT"
}

```

#### Are size values in pixel units always omitted?
In this [example: basic property font sizes](https://github.com/amzn/style-dictionary/blob/main/examples/basic/properties/size/font.json) it seems like `rem` or `em` are specified, but how would I know this?

#### Should colors always be specified as a hex value?
- What is with alpha values?
- should the type of color value be specified if other than hex?
- **Note:** I just found this: https://github.com/amzn/style-dictionary/blob/main/lib/common/transforms.js#L103 however I did not find where this is specified.

#### Specific categories
It seems there are expected categories to allow for transformation (https://github.com/amzn/style-dictionary/blob/main/lib/common/transforms.js#L20). However I can not find any place in the documentation where they are specified. I think this would be very helpful to add to the documentation.

I am very happy to help work on this if this would be helpful @Danny Banks. For example by sending PRs to the docs, opening new issues to discuss the aspects mentioned above, etc.

**Comment by chazzmoney** [comment]
@dbanksdesign Hey, I think that some figma support might be worth including as a goal in 3.0... Or you might have other suggestions since you have worked with SD and figma before.

**Comment by dbanksdesign** [comment]
Apologies for the lateness of this reply.... I definitely agree, better Figma support would be great in the next version of Style Dictionary. @lukasoppermann how far along are you on the Figma plugin? It might be easiest to set up Zoom call and we can go over these things. You can email me at djb at amazon dot com. Here are my answers

**How should units be specified?**

Units can be specified in the value, like "2rem". As you noticed in the next question, some of the examples don't have units and you can't really tell what unit they are specifying. This is because the transforms used in the configuration like 'size/remToPx' are simplistic in that they just parse the value for a number and assume it is either pixels or rems.

**Are size values in pixel units always omitted?**

Not necessarily, but because all the transforms right now make assumptions of what unit they are specifying by which transform you are using in your config, specifying a unit is not necessary. The size transforms right now are just parsing for a number, so technically you could have "12rem", "12px", or "12pixels" and the would all be parsed to the number 12, and then based on which transform is run could output "12px", "144px", or "0.75rem".

In this PR we discuss making more generic size transforms that don't assume all values are either  px or rem: [https://github.com/amzn/style-dictionary/pull/491](https://github.com/amzn/style-dictionary/pull/491) With the addition of those, a user could use both rem and px values by specifying the unit in the value. 

**Should colors always be specified as a hex value?**

Colors can be specified as a hex or as any string or object that [tinycolor](https://www.npmjs.com/package/tinycolor2) can understand. Here is an example using an object with HSLA values: [https://github.com/amzn/style-dictionary/blob/3.0/examples/advanced/transitive-transforms/tokens/color/core.json5](https://github.com/amzn/style-dictionary/blob/3.0/examples/advanced/transitive-transforms/tokens/color/core.json5)

Agree there should be better documentation around this. 

**How should gradient fills be specified?**

We don't yet have a built-in way to deal with gradients right now. But as you can with the previous answers, just because there is no built-in way doesn't mean we can't handle it 🙂. However gradients are an interesting problem because they are a bit complex and could potentially be defined in a few different ways. I'd love to hear ideas how to best define a gradient in a way that could be transformed to different platforms.

**How should shadows & effects be specified?**

For shadows again, there is not a built-in way yet. But we have been discussing that in these 2 issues:

* [https://github.com/amzn/style-dictionary/issues/455](https://github.com/amzn/style-dictionary/issues/455)
* [https://github.com/amzn/style-dictionary/issues/456](https://github.com/amzn/style-dictionary/issues/456)

Defining the structure of a shadow that can be transformed to different platforms would be great to have built-in transforms for. I'm not sure about effects, do you have examples of the types of effects that you are thinking?

**How corner radii be specified?**

Because radii are a size, under the CTI structure they would go under the "size" namespace.  

**How borders / strokes be specified?**

I specify borders like this:

```json
{
	"border": {
		"primary": {
			"value": {
				"width": "1px",
				"style": "solid",
				"color": "{color.base.neutral.10.value}"
			}
		}
	}
}
```

Again, there aren't built-in transformers for borders yet, but that would be good to add. 

**Specific categories**

Agreed, we should definitely have better documentation about the categories and types the built-in transforms and formats can handle.

If you want to help with any of these things, that would be amazing. The most helpful would be helping out to define the structure for shadow, effect, and gradient tokens. But we will take any help we can get. Feel free to open PRs for anything you think would be helpful.

**Comment by chemoish** [comment]
Hey, @dbanksdesign. Thank you so much for the examples. 

I don't understand enough about the build lifecycle to recommend a solve, but have you tested `transitive: true` with `outputReferences: true`? In this case the `value` is an `Object` and not a `String` and an error is thrown.

* What mechanism would be required if you wanted to pass a reference through a transform?
* Does it even make sense to generate references for custom values?

https://github.com/amzn/style-dictionary/blob/7a28f40b7f44b37e565b1360683b60268d044e9e/examples/advanced/transitive-transforms/sd.config.js#L53

```js
options: {
  outputReferences: true,
},
```

**Output**

```sh
⋊> ~/g/s/e/a/transitive-transforms on 3.0 ⨯ yarn build                                                                                                                                                                              14:04:33
yarn run v1.22.10
$ style-dictionary build --config ./sd.config.js

css
{ h: '{hue.red}', s: '{saturation.1}', l: '{lightness.1}' }
/Users/c0h04ba/git/style-dictionary/examples/advanced/transitive-transforms/node_modules/style-dictionary/lib/utils/references/getReferences.js:45
  value.replace(regex, function(match, variable) {
        ^

TypeError: value.replace is not a function
    at Object.getReferences (/Users/c0h04ba/git/style-dictionary/examples/advanced/transitive-transforms/node_modules/style-dictionary/lib/utils/references/getReferences.js:45:9)
    at sorter (/Users/c0h04ba/git/style-dictionary/examples/advanced/transitive-transforms/node_modules/style-dictionary/lib/common/formatHelpers/sortByReference.js:38:34)
    at Array.sort (<anonymous>)
    at formattedVariables (/Users/c0h04ba/git/style-dictionary/examples/advanced/transitive-transforms/node_modules/style-dictionary/lib/common/formatHelpers/formattedVariables.js:55:40)
    at Object.css/variables [as format] (/Users/c0h04ba/git/style-dictionary/examples/advanced/transitive-transforms/node_modules/style-dictionary/lib/common/formats.js:47:7)
    at buildFile (/Users/c0h04ba/git/style-dictionary/examples/advanced/transitive-transforms/node_modules/style-dictionary/lib/buildFile.js:101:37)
    at /Users/c0h04ba/git/style-dictionary/examples/advanced/transitive-transforms/node_modules/style-dictionary/lib/buildFiles.js:33:7
    at Array.forEach (<anonymous>)
    at buildFiles (/Users/c0h04ba/git/style-dictionary/examples/advanced/transitive-transforms/node_modules/style-dictionary/lib/buildFiles.js:31:18)
    at Object.buildPlatform (/Users/c0h04ba/git/style-dictionary/examples/advanced/transitive-transforms/node_modules/style-dictionary/lib/buildPlatform.js:62:3)
error Command failed with exit code 1.
```

**Comment by dbanksdesign** [comment]
@chemoish that is a good point we didn't think about building those 2 features... I created a new issue #615 to look into this further...
