### ISSUE TITLE
Allow testing with a mocked filesystem

### ISSUE THREAD

**Issue by tlouisse** [amzn/style-dictionary#528]
Currently I'm writing tests for my custom transforms, formatters and filters.

For simplicity and readability I use [mock-fs](https://www.npmjs.com/package/mock-fs) to mock the filesystem.
In a test, this looks something like:

```js
     mockFsAndRequire({
        '/my/dictionary/mixin.json': JSON.stringify({
          elevation: {
            l0: {
              shadow: { value: 'none', propRole: 'shadow' },
              bgcolor: { value: 'currentcolor', propRole: 'bgColor' },
            },
            l1: {
           ...etc..
```

However, it is currently not compatible. I get this error:
```js
Error: Cannot find module '/my/dictionary/mixin.json'
Require stack:
- /path/to/current/wd/noop.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
      at resolveFileName (node_modules/resolve-cwd/node_modules/resolve-from/index.js:29:39)
      at resolveFrom (node_modules/resolve-cwd/node_modules/resolve-from/index.js:43:9)
      at module.exports (node_modules/resolve-cwd/node_modules/resolve-from/index.js:46:47)
      at module.exports (node_modules/resolve-cwd/index.js:4:30)
      at combineJSON (node_modules/style-dictionary/lib/utils/combineJSON.js:42:24)
      at Object.extend (node_modules/style-dictionary/lib/extend.js:117:17)
      at runDictionary (dictionary/runDictionary.js:119:41)
      at Context.<anonymous> (dictionary/test-node/runDictionary.test.js:110:7)
      at processImmediate (node:internal/timers:463:21)
```

When I dive into the code, I see that `resolve-cwd` creates this problem: https://github.com/amzn/style-dictionary/blob/main/lib/utils/combineJSON.js#L41
When I use `path.resolve(process.cwd(), myPath)` instead, everything just works as expected.
Also, all tests keep working as expected.

Would it be possible to do a small code change here?

**Comment by tlouisse** [comment]
Closing the issue, since the pull request has been merged: https://github.com/amzn/style-dictionary/pull/529
Thanks for helping out! 👍
