### ISSUE TITLE
[Help] Options.platform is undefined in function buildAllPlatforms.js

### ISSUE THREAD

**Issue by estellouhou** [amzn/style-dictionary#680]
Hello 🤙

## Context
I'm currently setting up a repository to generate our tokens for multiple platform and brands. 

## Issues
My tokens are correctly generated. However, I have this errors with the function `buildAllPlatforms` after doing a build with style-dictionary:
```
Build completed!
>>>> buildAllPlatforms *** this.options {}
/Users/estelle/Projects/design-tokens/node_modules/style-dictionary/lib/buildAllPlatforms.js:31
  Object.keys(this.options.platforms).forEach(function (key) {
         ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.buildAllPlatforms (/Users/estelle/Projects/design-tokens/node_modules/style-dictionary/lib/buildAllPlatforms.js:31:10)
    at Command.styleDictionaryBuild (/Users/estelle/Projects/design-tokens/node_modules/style-dictionary/bin/style-dictionary:91:21)
    at Command.listener [as _actionHandler] (/Users/estelle/Projects/design-tokens/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/Users/estelle/Projects/design-tokens/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/Users/estelle/Projects/design-tokens/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/Users/estelle/Projects/design-tokens/node_modules/commander/index.js:882:12)
    at Command.parse (/Users/estelle/Projects/design-tokens/node_modules/commander/index.js:717:10)
    at Object.<anonymous> (/Users/estelle/Projects/design-tokens/node_modules/style-dictionary/bin/style-dictionary:111:9)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
error Command failed with exit code 1.
```
## Current config.js:
```
const StyleDictionaryPackage = require("style-dictionary");

// HAVE THE STYLE DICTIONARY CONFIG DYNAMICALLY GENERATED

function getStyleDictionaryConfig(brand, platform) {
  return {
    source: [`tokens/brands/${brand}/**/*.json`, "tokens/globals/**/*.json"],
    platforms: {
      web: {
        transformGroup: "web",
        buildPath: `dist/web/${brand}/`,
        files: [
          {
            destination: "_tokens.scss",
            format: "scss/variables",
          },
          {
            destination: "tokens.json",
            format: "json/nested",
          },
        ],
      },
      ios: {
        transformGroup: "ios",
        buildPath: `dist/ios/${brand}/`,
        files: [
          {
            destination: "tokens.h",
            format: "ios/macros",
          },
        ],
      },
    },
  };
}

console.log("Build started...");

// PROCESS THE DESIGN TOKENS FOR THE DIFFERENT BRANDS AND PLATFORMS

["brand-1"].map(function (brand) {
  ["web", "ios", "android"].map(function (platform) {
    console.log("\n==============================================");
    console.log(`\nProcessing: [${platform}] [${brand}]`);

    const StyleDictionary = StyleDictionaryPackage.extend(
      getStyleDictionaryConfig(brand, platform)
    );

    StyleDictionary.buildPlatform(platform);

    console.log("\nEnd processing");
  });
});

console.log("\n==============================================");
console.log("\nBuild completed!");

```

## Code structure
![Capture d’écran 2021-08-13 à 18 20 01](https://user-images.githubusercontent.com/71654148/129389462-b58c4417-60c9-434e-b19b-4fa3cf0dd726.png)

## Error found from style-dictionary
Please note that `options` is an empty object.

![Capture d’écran 2021-08-13 à 18 22 03](https://user-images.githubusercontent.com/71654148/129389685-45d9e4e4-9c51-49ea-b4d0-fb1344171107.png)

I look forward to see what I have done wrong.
Thanks for your help and, 
Take care <3

**Comment by chazzmoney** [comment]
I only had time for a quick glance, but two possibilities I can see:

1. You are trying to use the CLI to run a node structured style-dictionary usage, instead of calling it from a node command.
2. You should be using "buildAllPlatforms" instead of "buildPlatform"
