### ISSUE TITLE
Error while building dictionary using "style-dictionary build"

### ISSUE THREAD

**Issue by JanisOzolins** [amzn/style-dictionary#850]
```
Build completed!
/Users/my_user/.nvm/versions/node/v14.16.0/lib/node_modules/style-dictionary/lib/buildAllPlatforms.js:30
  Object.keys(this.options.platforms).forEach(function (key) {
         ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.buildAllPlatforms (/Users/my_user/.nvm/versions/node/v14.16.0/lib/node_modules/style-dictionary/lib/buildAllPlatforms.js:30:10)
    at Command.styleDictionaryBuild (/Users/my_user/.nvm/versions/node/v14.16.0/lib/node_modules/style-dictionary/bin/style-dictionary:91:21)
    at Command.listener [as _actionHandler] (/Users/my_user/.nvm/versions/node/v14.16.0/lib/node_modules/style-dictionary/node_modules/commander/lib/command.js:488:17)
    at /Users/my_user/.nvm/versions/node/v14.16.0/lib/node_modules/style-dictionary/node_modules/commander/lib/command.js:1227:65
    at Command._chainOrCall (/Users/my_user/.nvm/versions/node/v14.16.0/lib/node_modules/style-dictionary/node_modules/commander/lib/command.js:1144:12)
    at Command._parseCommand (/Users/my_user/.nvm/versions/node/v14.16.0/lib/node_modules/style-dictionary/node_modules/commander/lib/command.js:1227:27)
    at Command._dispatchSubcommand (/Users/my_user/.nvm/versions/node/v14.16.0/lib/node_modules/style-dictionary/node_modules/commander/lib/command.js:1050:25)
    at Command._parseCommand (/Users/my_user/.nvm/versions/node/v14.16.0/lib/node_modules/style-dictionary/node_modules/commander/lib/command.js:1193:19)
    at Command.parse (/Users/my_user/.nvm/versions/node/v14.16.0/lib/node_modules/style-dictionary/node_modules/commander/lib/command.js:897:10)
```

build.js
```
const getStyleDictionaryConfig = {
  source: ['styles/tokens/input/**/*.json'],
  platforms: {
    scss: {
      transformGroup: 'custom/scss',
      buildPath: 'styles/tokens/',
      prefix: 'token',
      files: [
        {
          destination: `_variables.scss`,
          format: 'scss/variables',
          filter: (prop) => prop.type !== 'composition',
        },
        {
          destination: '_mixins.scss',
          format: 'mixin-scss/variables',
          filter: (prop) => prop.type === 'composition',
        },
      ],
    },
  },
}

// --- more registerTransform here ----

// APPLY THE CONFIGURATION
// IMPORTANT: the registration of custom transforms
// needs to be done _before_ applying the configuration
const StyleDictionaryExtended = StyleDictionary.extend(getStyleDictionaryConfig)

// FINALLY, BUILD ALL THE PLATFORMS
StyleDictionaryExtended.buildPlatform('scss')

console.log('\n==============================================')
console.log('\nBuild completed!')

```

The plugin is doing what it's supposed to, but why is it throwing this TypeError?

I am running the script using command `style-dictionary build --config=build.js`. But the error seems to not be there when I run `node ./build.js` 🤔

**Comment by daviddurre** [comment]
I'm seeing the same error. The build is completed but then I see the same error.

**Comment by shroy** [comment]
I am seeing this as well. It wasn't happening until I introduced a separate `.js` config file and ran the same command as the OP.

**Comment by mi-upto** [comment]
@JanisOzolins
me too, i done the same thing...
check the document. plz.
config arguments only JSON is allowed. 😄 


> Set the config file to use. Must be a .json file
> https://github.com/amzn/style-dictionary#usage

**Comment by jorenbroekema** [comment]
What @mi-upto said :)
